# SPDX-FileCopyrightText: 2026 DevLibrary Contributors
# SPDX-License-Identifier: Apache-2.0

"""Human error context for CLI API operations."""

from __future__ import annotations

import inspect
from pathlib import Path

OPERATION_LABELS = {
    "_act": "Update inbox item",
    "_add_co_author": "Add co-author",
    "_archive_agent": "Archive agent",
    "_archive_component": "Archive component",
    "_collect_mcp_env_vars": "Read MCP environment requirements",
    "_collect_mcp_headers": "Read MCP header requirements",
    "_emit": "List recommendations",
    "_emit_list": "List inbox items",
    "_feedback_impl": "Show registry feedback",
    "_fetch_registry_items": "Fetch registry components",
    "_find_pending_request": "Find teamspace join request",
    "_install_impl": "Install MCP server",
    "_list_co_authors": "List co-authors",
    "_list_impl": "List MCP servers",
    "_owner": "Resolve bulk component owner",
    "_rate_delete": "Delete registry feedback",
    "_rate_impl": "Submit registry feedback",
    "_rate_update": "Update registry feedback",
    "_recent_remote": "Read recent server logs",
    "_registry_name": "Read registry name",
    "_remove_co_author": "Remove co-author",
    "_render_sessions_detail": "Show trace details",
    "_report_to_inbox": "Report outdated items",
    "_resolve_agent_id": "Resolve insight agent",
    "_resolve_listing_id": "Resolve registry item",
    "_resolve_report_for_show": "Resolve insight report",
    "_show_impl": "Show MCP server",
    "_submit_impl": "Submit MCP server",
    "_top_impl": "List top registry items",
    "_traces_impl": "List traces",
    "_unarchive_component": "Restore component",
    "add_member": "Add teamspace member",
    "admin_audit_log": "List audit events",
    "admin_audit_log_export": "Export audit events",
    "_admin_user": "Find administrator-managed user",
    "admin_cache_clear": "Clear server caches",
    "admin_create_user": "Create user",
    "admin_delete_user": "Delete user",
    "admin_diagnostics": "Read server diagnostics",
    "admin_reset_password": "Reset user password",
    "admin_saml_config": "Read SAML configuration",
    "admin_saml_config_delete": "Delete SAML configuration",
    "admin_saml_config_set": "Update SAML configuration",
    "admin_scim_token_create": "Create SCIM token",
    "admin_scim_token_revoke": "Revoke SCIM token",
    "admin_scim_tokens": "List SCIM tokens",
    "admin_security_events": "List security events",
    "admin_set": "Update server setting",
    "admin_set_role": "Update user role",
    "admin_settings": "List server settings",
    "admin_trace_privacy": "Read trace privacy setting",
    "admin_trace_privacy_set": "Update trace privacy setting",
    "admin_users": "List users",
    "agent_build": "Validate agent",
    "agent_bulk_create": "Bulk create agents",
    "agent_create": "Create agent",
    "agent_install": "Generate agent installation",
    "agent_list": "List agents",
    "agent_my": "List owned agents",
    "agent_publish": "Publish agent",
    "agent_release": "Release agent version",
    "agent_show": "Show agent",
    "agent_unarchive": "Restore agent",
    "agent_versions": "List agent versions",
    "approve_join_request": "Approve teamspace join request",
    "api_request": "Call DevLibrary API",
    "approve_visibility_request": "Approve teamspace visibility",
    "bulk_submit_components": "Bulk submit components",
    "bundle": "Generate support bundle",
    "change_password": "Change password",
    "claim_personal_teamspace": "Claim personal teamspace",
    "create_invite": "Create teamspace invite",
    "create_team": "Create teamspace",
    "delete_invite": "Delete teamspace invite",
    "delete_team": "Delete teamspace",
    "edit_mcp": "Edit MCP server",
    "hook_edit": "Edit hook",
    "hook_install": "Install hook",
    "hook_list": "List hooks",
    "hook_show": "Show hook",
    "hook_submit": "Submit hook",
    "inbox_count": "Count inbox items",
    "inbox_read_all": "Mark inbox items read",
    "inbox_show": "Show inbox item",
    "insights_generate": "Generate insight report",
    "insights_list": "List insight reports",
    "leave_team": "Leave teamspace",
    "list_invite_requests": "List teamspace invite requests",
    "list_invites": "List teamspace invites",
    "list_join_requests": "List teamspace join requests",
    "list_members": "List teamspace members",
    "list_my_join_requests": "List personal teamspace join requests",
    "list_teams": "List teamspaces",
    "list_visibility_requests": "List teamspace visibility requests",
    "mcp_my": "List owned MCP servers",
    "outdated": "Check installed versions",
    "plan_lockfile_reconciliation": "Reconcile installed registry state",
    "prompt_edit": "Edit prompt",
    "prompt_list": "List prompts",
    "prompt_my": "List owned prompts",
    "prompt_render": "Render prompt",
    "prompt_show": "Show prompt",
    "prompt_submit": "Submit prompt",
    "pull": "Pull agent",
    "preview_invite": "Preview teamspace invite",
    "recommend_dismiss": "Update recommendation feedback",
    "reject_join_request": "Reject teamspace join request",
    "reject_visibility_request": "Reject teamspace visibility",
    "remove_member": "Remove teamspace member",
    "request_join": "Request teamspace access",
    "request_via_invite": "Request teamspace access via invite",
    "review_approve": "Approve review",
    "review_list": "List pending reviews",
    "review_reject": "Reject review",
    "review_show": "Show review",
    "revoke_invite": "Revoke teamspace invite",
    "sandbox_edit": "Edit sandbox",
    "sandbox_list": "List sandboxes",
    "sandbox_show": "Show sandbox",
    "sandbox_submit": "Submit sandbox",
    "workflow_edit": "Edit workflow",
    "workflow_install": "Install workflow",
    "workflow_list": "List workflows",
    "workflow_show": "Show workflow",
    "workflow_submit": "Submit workflow",
    "set_username": "Update username",
    "set_visibility": "Update teamspace visibility",
    "show_team": "Show teamspace",
    "skill_edit": "Edit skill",
    "skill_install": "Install skill",
    "skill_list": "List skills",
    "skill_my": "List owned skills",
    "skill_show": "Show skill",
    "skill_submit": "Submit skill",
    "submit": "Submit MCP server draft",
    "telemetry_status": "Check telemetry status",
    "transfer_owner": "Transfer registry ownership",
    "version_list": "List component versions",
    "version_publish": "Publish component version",
    "whoami": "Show current user",
    "withdraw_join_request": "Withdraw teamspace join request",
}

RESOURCE_LABELS = {
    "cmd_agent.py": "agent registry",
    "cmd_api.py": "DevLibrary API",
    "cmd_archive.py": "registry component",
    "cmd_bulk.py": "component registry",
    "cmd_auth.py": "user account",
    "cmd_co_authors.py": "registry co-authors",
    "cmd_component.py": "component versions",
    "cmd_hook.py": "hook registry",
    "cmd_inbox.py": "user inbox",
    "cmd_insights.py": "agent insights",
    "cmd_mcp.py": "MCP registry",
    "cmd_migrate.py": "migration authorization",
    "cmd_logs.py": "server logs",
    "cmd_ops.py": "DevLibrary operations",
    "cmd_outdated.py": "installed registry items",
    "cmd_prompt.py": "prompt registry",
    "cmd_pull.py": "agent installation",
    "cmd_recommend.py": "registry recommendations",
    "cmd_sandbox.py": "sandbox registry",
    "cmd_workflow.py": "workflow registry",
    "cmd_server.py": "server administration",
    "cmd_support.py": "support bundle",
    "cmd_skill.py": "skill registry",
    "cmd_team.py": "teamspaces",
    "cmd_transfer.py": "registry ownership",
    "lockfile_reconcile.py": "installed registry state",
}


def caller_context(default_operation: str, default_resource: str) -> tuple[str, str]:
    """Resolve the first CLI caller to its audited human labels."""
    frame = inspect.currentframe()
    try:
        frame = frame.f_back if frame else None
        while frame:
            module = str(frame.f_globals.get("__name__", ""))
            if module not in {"dev_library_cli.client", __name__}:
                function = frame.f_code.co_name
                filename = Path(frame.f_code.co_filename).name
                return OPERATION_LABELS.get(function, default_operation), RESOURCE_LABELS.get(
                    filename, default_resource
                )
            frame = frame.f_back
    finally:
        del frame
    return default_operation, default_resource
