# SPDX-FileCopyrightText: 2026 Subramania Raja <dhanpraja231@gmail.com>
# SPDX-FileCopyrightText: 2026 Hari Srinivasan <harisrini21@gmail.com>
# SPDX-FileCopyrightText: 2026 Naraen Rammoorthi <naraen13@gmail.com>
# SPDX-FileCopyrightText: 2026 Santhosh Raja <santhoshpkraja2004@gmail.com>
# SPDX-FileCopyrightText: 2026 Shaan Narendran <shaannaren06@gmail.com>
# SPDX-License-Identifier: Apache-2.0

import json
import logging
import os
import re
import shutil
import tomllib
from pathlib import Path
from tempfile import NamedTemporaryFile

from observal_cli.errors import ErrorCategory, fail
from observal_shared.secrets import resolve_secret

logger = logging.getLogger(__name__)

_CONFIG_DIR_DEFAULT = Path.home() / ".dev-library"


def _migrate_legacy_config_dir() -> Path:
    """One-time migration: move ~/.dev-library to ~/.dev-library when only the legacy dir exists."""
    legacy = Path.home() / ".observal"
    if not _CONFIG_DIR_DEFAULT.exists() and legacy.exists():
        try:
            legacy.rename(_CONFIG_DIR_DEFAULT)
        except OSError:
            return legacy
    return _CONFIG_DIR_DEFAULT


CONFIG_DIR = _migrate_legacy_config_dir()
CONFIG_FILE = CONFIG_DIR / "config.json"
ALIASES_FILE = CONFIG_DIR / "aliases.json"
LAST_RESULTS_FILE = CONFIG_DIR / "last_results.json"

_LEGACY_MCP_CONFIGS = (
    ".claude.json",
    ".cursor/mcp.json",
    ".kiro/settings/mcp.json",
    ".codex/config.toml",
    ".vscode/mcp.json",
    ".copilot/mcp-config.json",
    ".config/opencode/opencode.json",
    "opencode.json",
    ".gemini/antigravity-cli/mcp_config.json",
    ".agents/mcp_config.json",
    ".pi/agent/mcp.json",
    ".pi/mcp.json",
)

PUBLIC_SERVER_URL = "https://public.observal.io"

DEFAULTS = {
    "server_url": "",
    "access_token": "",
    "refresh_token": "",
    "timeout": 30,
    "update_check": True,
    "update_check_interval": 86400,  # seconds (24h)
    "update_check_repo": "",  # empty = Observal/DevLibrary
}


def _unwrap_mcp_entry(entry: dict) -> bool:
    """Replace one legacy wrapper command with its original MCP command."""
    command = entry.get("command")
    if command == "observal-shim":
        args = entry.get("args") or []
        if "--" not in args:
            raise ValueError("wrapped MCP entry has no command delimiter")
        original = args[args.index("--") + 1 :]
        if not original:
            raise ValueError("wrapped MCP entry has no original command")
        entry["command"] = original[0]
        entry["args"] = original[1:]
        return True

    if isinstance(command, list) and command and command[0] == "observal-shim":
        if "--" not in command:
            raise ValueError("wrapped MCP command has no command delimiter")
        original = command[command.index("--") + 1 :]
        if not original:
            raise ValueError("wrapped MCP command has no original command")
        entry["command"] = original
        entry.pop("args", None)
        return True

    return False


def _unwrap_mcp_tree(value) -> bool:
    """Recursively unwrap MCP entries in JSON or TOML configuration data."""
    changed = False
    if isinstance(value, dict):
        changed = _unwrap_mcp_entry(value)
        for child in value.values():
            changed = _unwrap_mcp_tree(child) or changed
    elif isinstance(value, list):
        for child in value:
            changed = _unwrap_mcp_tree(child) or changed
    return changed


def _unwrap_toml_text(text: str) -> str:
    """Unwrap the single-line TOML entries generated by older DevLibrary releases."""
    pattern = re.compile(
        r'(?m)^(?P<command_indent>[ \t]*)command[ \t]*=[ \t]*"observal-shim"[ \t]*\n'
        r"(?P<args_indent>[ \t]*)args[ \t]*=[ \t]*(?P<args>\[[^\n]*\])[ \t]*$"
    )

    def replace(match: re.Match) -> str:
        args = json.loads(match.group("args"))
        if "--" not in args:
            raise ValueError("wrapped MCP entry has no command delimiter")
        original = args[args.index("--") + 1 :]
        if not original:
            raise ValueError("wrapped MCP entry has no original command")
        return (
            f"{match.group('command_indent')}command = {json.dumps(original[0])}\n"
            f"{match.group('args_indent')}args = {json.dumps(original[1:])}"
        )

    rendered, count = pattern.subn(replace, text)
    if count == 0:
        raise ValueError("wrapped MCP entry is not in a recognized generated TOML format")
    tomllib.loads(rendered)
    return rendered


def _migrate_mcp_config(path: Path) -> bool:
    text = path.read_text()
    if "observal-shim" not in text:
        return False

    if path.suffix == ".toml":
        rendered = _unwrap_toml_text(text)
    else:
        from observal_cli.shared.utils import load_jsonc

        data = load_jsonc(path)
        if not _unwrap_mcp_tree(data):
            return False
        rendered = json.dumps(data, indent=2) + "\n"

    backup = path.with_suffix(path.suffix + ".pre-unshim.bak")
    if not backup.exists():
        shutil.copy2(path, backup)
    temporary = path.with_name(path.name + ".unshim.tmp")
    temporary.write_text(rendered)
    shutil.copymode(path, temporary)
    temporary.replace(path)
    return True


def migrate_shimmed_mcp_configs(home: Path | None = None, cwd: Path | None = None) -> list[Path]:
    """Unwrap legacy MCP configs under the user home and current project."""
    home = home or Path.home()
    cwd = cwd or Path.cwd()
    candidates = {(base / relative).expanduser() for base in (home, cwd) for relative in _LEGACY_MCP_CONFIGS}
    migrated = []
    for path in sorted(candidates):
        if not path.is_file():
            continue
        try:
            if _migrate_mcp_config(path):
                migrated.append(path)
        except (OSError, ValueError, tomllib.TOMLDecodeError, json.JSONDecodeError) as exc:
            raise RuntimeError(f"failed to migrate wrapped MCP config {path}: {exc}") from exc
    return migrated


def _read_json_object(path: Path, *, operation: str) -> dict:
    try:
        data = json.loads(path.read_text())
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        fail(
            ErrorCategory.VALIDATION,
            "The JSON file is malformed.",
            operation=operation,
            resource=str(path),
            remediation="Repair or remove the file, then retry.",
            detail=repr(exc),
        )
    if not isinstance(data, dict):
        fail(
            ErrorCategory.VALIDATION,
            "The JSON file must contain an object.",
            operation=operation,
            resource=str(path),
            remediation="Replace the file contents with a JSON object and retry.",
        )
    return data


def _write_json(path: Path, data: dict) -> None:
    """Atomically write a JSON object with owner-only permissions."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary: Path | None = None
    try:
        with NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, prefix=f".{path.name}.", delete=False) as file:
            temporary = Path(file.name)
            json.dump(data, file, indent=2)
            file.flush()
            os.fsync(file.fileno())
        temporary.chmod(0o600)
        temporary.replace(path)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def load_persisted() -> dict:
    """Load only on-disk config values, without environment overrides."""
    if not CONFIG_FILE.exists():
        return {}
    stored = _read_json_object(CONFIG_FILE, operation="Load CLI configuration")
    stored.pop("output", None)
    stored.pop("color", None)
    return stored


def load() -> dict:
    """Load config from disk and apply environment variable overrides."""
    cfg = {**DEFAULTS, **load_persisted()}

    if env_url := os.environ.get("DEVLIBRARY_SERVER_URL"):
        cfg["server_url"] = env_url
    for name in ("OBSERVAL_ACCESS_TOKEN", "OBSERVAL_API_KEY", "DEVLIBRARY_TOKEN"):
        try:
            token = resolve_secret(name)
        except ValueError as exc:
            fail(
                ErrorCategory.VALIDATION,
                f"{name} is configured incorrectly.",
                operation="Load CLI configuration",
                resource=name,
                remediation=f"Set only {name} or {name}_FILE, then retry.",
                detail=repr(exc),
            )
        if token:
            cfg["access_token"] = token

    return cfg


def _write_config(data: dict) -> None:
    try:
        _write_json(CONFIG_FILE, data)
    except PermissionError as error:
        fail(
            ErrorCategory.PERMISSION,
            f"Cannot write {error.filename or CONFIG_FILE}: permission denied.",
            operation="Save CLI configuration",
            resource=str(error.filename or CONFIG_FILE),
            remediation=f'If {CONFIG_DIR} is owned by root, run: sudo chown -R "$USER" "{CONFIG_DIR}"',
            detail=repr(error),
        )


def save(data: dict):
    """Save config to disk without persisting environment overrides."""
    existing = load_persisted()
    existing.update(data)
    existing.pop("output", None)
    existing.pop("color", None)
    _write_config(existing)


def remove(*keys: str) -> None:
    """Remove keys from the on-disk config without persisting environment overrides."""
    if not CONFIG_FILE.exists():
        return
    existing = load_persisted()
    for key in keys:
        existing.pop(key, None)
    _write_config(existing)


def get_timeout() -> int:
    """Get request timeout in seconds. Env var > config > default."""
    env_timeout = os.environ.get("DEVLIBRARY_TIMEOUT")
    if env_timeout:
        try:
            return int(env_timeout)
        except ValueError:
            logger.warning("Invalid DEVLIBRARY_TIMEOUT=%r, falling back to config/default", env_timeout)
    cfg = load()
    return int(cfg.get("timeout", 30))


def get_or_exit(*, require_auth: bool = True) -> dict:
    cfg = load()
    if not cfg.get("server_url") and not require_auth and not cfg.get("access_token"):
        cfg["server_url"] = PUBLIC_SERVER_URL
    if not cfg.get("server_url") or (require_auth and not cfg.get("access_token")):
        fail(
            ErrorCategory.AUTH if require_auth else ErrorCategory.USAGE,
            "Not configured. DevLibrary authentication is required."
            if require_auth
            else "No DevLibrary server is configured.",
            operation="Load authenticated CLI configuration" if require_auth else "Load CLI configuration",
            resource=str(CONFIG_FILE),
            remediation=(
                "Run dev-library auth login or set DEVLIBRARY_TOKEN or OBSERVAL_ACCESS_TOKEN."
                if require_auth
                else "Set DEVLIBRARY_SERVER_URL or run dev-library config set server_url URL."
            ),
        )
    return cfg


# ── Aliases ──────────────────────────────────────────────


def load_aliases() -> dict[str, str]:
    if not ALIASES_FILE.exists():
        return {}
    aliases = _read_json_object(ALIASES_FILE, operation="Load CLI aliases")
    if not all(isinstance(name, str) and isinstance(target, str) for name, target in aliases.items()):
        fail(
            ErrorCategory.VALIDATION,
            "Every alias and target must be a string.",
            operation="Load CLI aliases",
            resource=str(ALIASES_FILE),
            remediation="Repair or remove the aliases file, then retry.",
        )
    return aliases


def save_aliases(aliases: dict[str, str]):
    _write_json(ALIASES_FILE, aliases)


# ── Last results cache ───────────────────────────────────


def save_last_results(items: list[dict], item_type: str | None = None) -> None:
    """Cache list results and the registry type that produced them."""
    cache = {
        "item_type": item_type,
        "ids": [str(item["id"]) for item in items],
        "names": {item.get("name", "").lower(): str(item["id"]) for item in items if item.get("name")},
    }
    _write_json(LAST_RESULTS_FILE, cache)


def load_last_results() -> dict:
    if not LAST_RESULTS_FILE.exists():
        return {"item_type": None, "ids": [], "names": {}}
    data = _read_json_object(LAST_RESULTS_FILE, operation="Load CLI list results")
    ids = data.get("ids")
    names = data.get("names")
    item_type = data.get("item_type")
    if (
        not isinstance(ids, list)
        or not all(isinstance(item, str) for item in ids)
        or not isinstance(names, dict)
        or not all(isinstance(name, str) and isinstance(item, str) for name, item in names.items())
        or (item_type is not None and not isinstance(item_type, str))
    ):
        fail(
            ErrorCategory.VALIDATION,
            "The cached CLI list results are malformed.",
            operation="Load CLI list results",
            resource=str(LAST_RESULTS_FILE),
            remediation="Remove the results cache and run the list command again.",
        )
    return {"item_type": item_type, "ids": ids, "names": names}


# ── Universal resolver ───────────────────────────────────


def resolve_alias(name: str, expected_type: str | None = None) -> str:
    """Resolve an alias or a type-scoped row number to its stored reference."""
    # @alias
    if name.startswith("@"):
        aliases = load_aliases()
        resolved = aliases.get(name[1:])
        if resolved:
            return resolved
        fail(
            ErrorCategory.NOT_FOUND,
            f"Alias {name} is not configured.",
            operation="Resolve CLI alias",
            resource=name,
            remediation=f"Run dev-library config alias {name[1:]} <reference> to create it.",
        )

    # Row number from last list (positional shortcut only)
    if name.isdigit():
        cache = load_last_results()
        cached_type = cache.get("item_type")
        if expected_type and cached_type != expected_type:
            fail(
                ErrorCategory.NOT_FOUND,
                f"Row {name} is not from the latest {expected_type} list.",
                operation="Resolve CLI row reference",
                resource=name,
                remediation=f"Run the {expected_type} list command and retry with one of its row numbers.",
            )
        idx = int(name)
        ids = cache.get("ids", [])
        if 1 <= idx <= len(ids):
            return ids[idx - 1]
        fail(
            ErrorCategory.NOT_FOUND,
            f"Row {name} does not exist in the latest list results.",
            operation="Resolve CLI row reference",
            resource=name,
            remediation="Run the relevant list command and retry with one of its row numbers.",
        )

    # Pass names through as-is. The server resolves names natively.
    # Previously we looked up names in a local cache (last_results.json),
    # but that cache goes stale after a database reset, causing 404s
    # when the same name gets a new UUID.
    return name
